### ISSUE TITLE
Place of birth input margins

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#970]
- [x] Place of birth inputs have larger margins than other form inputs.
<img width="997" alt="screen shot 2017-04-13 at 3 50 25 pm" src="https://cloud.githubusercontent.com/assets/19935974/25021805/6a3c79fc-2061-11e7-9f85-aef01c724910.png">
<img width="960" alt="screen shot 2017-04-13 at 3 50 30 pm" src="https://cloud.githubusercontent.com/assets/19935974/25021806/6a446978-2061-11e7-9609-e6a9a71348f5.png">

Since they are "connected" inputs they should have the margins like other "connected" inputs.
Example:
<img width="863" alt="screen shot 2017-04-13 at 3 52 40 pm" src="https://cloud.githubusercontent.com/assets/19935974/25021803/66b10d7a-2061-11e7-983f-5947f04c84fe.png">

**Comment by bmallred** [comment]
If something is wrapped with a help message then they have that bottom margin applied... does this need be changed?

**Comment by Jay-Neighbours-I72** [comment]
@bmallred yeah, let's keep them consistent throughout for a cohesive feel.

When the help text is open we can make sure there is enough bottom margin on the help text to ensure it is associated with the input it is below

**Comment by bmallred** [comment]
From screen sharing session

```css
label { line-height: 1.6; }
.field > .table { width: 100%; }
.field { margin-bottom: 1.5rem; }
.field .title { margin-top: 5rem; }
.field:first .title { margin-top: 1.5rem; }
```
Also make the `.block` equal white-space left-right as top-bottom.
